# @package _global_

defaults:
  - _self_

wandb_project: new_sampler_test
deepspeed_config: ${oc.env:SPEECHLMM_ROOT}/conf/deepspeed/zero3.json

data:
  data_config_path: ${oc.env:SPEECHLMM_ROOT}/conf/datasets/multi_task.yml
  align_text_to_audio: false
  rebuild_dataset_cache: false
  restore_punctuation_and_spaces: true
  num_proc_for_preprocessing: 64
  task_weights:
    TextInstruct: 0.3
    # MultiTurnTextInstruct: 0.1
    ASR: 0.05
    ST: 0.05
    TTS: 0.6
    # S2ST: 0.3
  multi_task_sampler: alternating
  replacement: true
  variable_batch_size: false
  # max_length_per_batch: 3000
  group_dataset_by_task:
    train: true
  max_condition_audio_duration: 5

training:
  per_device_train_batch_size: 8
  save_steps: 2500
  save_total_limit: 5
  num_train_epochs: 10
  eval_steps: 0
  eval_strategy: "no"
  attn_implementation: flash_attention_2
  dataloader_num_workers: 0 # to avoid error w. whisper inference: RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
  mm_projector_lr: 5.0e-5
  learning_rate: 5.0e-5
  freeze_modules:
    - audio_encoder
    - codec_encoder
    - codec_decoder
  group_by_modality_length: false
  report_to: wandb

model:
  perturb_prob: 0.2
  pad_audio_weight: 1
  perturb_prob_decay: 0.5 # perturb_prob * (1 - t/T)^perturb_prob_decay
  # epad_audio_weight: 1
  # pad_epad_audio_weight_decay: 0.5 # pad_audio_weight * (1 - t/T)^pad_audio_weight_decay

  add_all_multimodal_tokens: true

  backfeeding_audio_adapter:
    audio_adapter:
      hidden_layers: 6
  talking_head:
    depformer_num_layers: 8
  conditioning_audio_adapter:
    num_hidden_layers: 6

  codebook_weights: [1, 1, 1, 1, 1, 1, 1, 1]

# ADD THIS IF YOU WANT TO USE TRAIN ALSO ON S2ST and/or ASR, ST
  audio_adapter:
    hidden_layers: 6

# python speechlmm/train/train_hydra.py \
#     --config-name pretrain \
#     model/audio_encoder=seamless \
#     model/codec_encoder=mimi \
#     model/codec_decoder=mimi \
#     model/audio_adapter=mlp \
#     model/backfeeding_audio_adapter=features \
#     model/conditioning_audio_adapter=qformer \
#     model/text_decoder=llama_3_8b \
#     model/talking_head=moshi_bert \
#     training_setting=speech2speech/moshi_bert_multi_task
