# @package _global_

defaults:
  - speechlmm/v1_warmup/base
  - override /model/text_decoder: llama_3_1b
  - _self_

run_name: speechlmm-s

training:
  per_device_train_batch_size: 32
  learning_rate: 1.0e-4
  save_steps: 1500
