# @package _global_

defaults:
  - speechlmm/v1/base
  - override /model/text_decoder: llama_3_70b
  - _self_

run_name: speechlmm-xl

training:
  per_device_train_batch_size: 8
  learning_rate: 2.5e-5
  save_steps: 6000
